### ISSUE TITLE
Unhanded exception 

### ISSUE THREAD

**Issue by m00dy-** [matterpreter/DefenderCheck#14]
Hello,
any idea about the cause of this error:
PS C:> .\DefenderCheck.exe C:\Temp\mimikatz.exe
Target file size: 1234696 bytes
Analyzing...

[!] Identified end of bad bytes at offset 0x2 in the original file

Unhandled Exception: System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at DefenderCheck.Program.HalfSplitter(Byte[] originalarray, Int32 lastgood)
   at DefenderCheck.Program.Main(String[] args)

**Comment by matterpreter** [comment]
Try adding `C:\Temp` as and exemption in Defender.

**Comment by jsarkisian** [comment]
Having a similar issue:

![image](https://user-images.githubusercontent.com/46200265/99450071-3fa46d00-28ee-11eb-98ff-ee8b3806f7a8.png)

I tried adding C:\Temp as an exception but am still getting the above error. Thanks!

**Comment by morzen** [comment]
how did you even manage to get the .exe file cause I can't find it personally?

**Comment by jsarkisian** [comment]
You have to compile it using Visual Basic or MSBuild. Easier than it sounds, just import the SLN file to VB and click build and you’ll get an EXE.

**Comment by sp00ks-git** [comment]
> You have to compile it using Visual Basic or MSBuild. Easier than it sounds, just import the SLN file to VB and click build and you’ll get an EXE.

Visual Studio not Visual Basic

**Comment by ahmedhawaryhawary** [comment]
> 
> 
> Hello,
> any idea about the cause of this error:
> PS C:> .\DefenderCheck.exe C:\Temp\mimikatz.exe
> Target file size: 1234696 bytes
> Analyzing...
> 
> [!] Identified end of bad bytes at offset 0x2 in the original file
> 
> Unhandled Exception: System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
> at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
> at DefenderCheck.Program.HalfSplitter(Byte[] originalarray, Int32 lastgood)
> at DefenderCheck.Program.Main(String[] args)

Note: Defender must be enabled on your system, but the realtime protection and automatic sample submission features should be disabled.
Exit any other AV

**Comment by ahmedhawaryhawary** [comment]
for Compiling 
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe "Project Path/DefenderCheck.csproj"

**Comment by matterpreter** [comment]
Seems like this issue has moved from an issue with Defender to issues with compiling DefenderCheck. I'm going to close this issue as @m00dy- has not responded.
