### ISSUE TITLE
The program is not working properly

### ISSUE THREAD

**Issue by Knakiri** [matterpreter/DefenderCheck#28]
i used this program on my vm (win11 updated windows defender) and try to scan my payload it said it was undetected but when my friend tried to download the payload it got detected in scantime the payload was downloaded in vm with upload.ee and the defendercheck too what did i do wrong?

**Comment by matterpreter** [comment]
I have no idea. I doubt that there was a change to the signatures between the two versions and I don't really have enough information to debug. It sounds like this is an issue with your host and not the tool, so I'm going to close this issue. Feel free to open a new issue if the issue persists and you can provide more technical details.
