### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by threst** [matterpreter/DefenderCheck#9]
Thanks for this amazing tool. I tested it yesterday. Thank you for your help.

C:\Users\DefenderCheck\DefenderCheck\DefenderCheck\bin\Release>DefenderCheck.exe
Unhandled Exception: System.NullReferenceException: The object reference was not set to an instance of the object.
    In the DefenderCheck.Program.Setup() location C:\Users\DefenderCheck\DefenderCheck\DefenderCheck\Program.cs: line number 65
    In the DefenderCheck.Program.Main(String[] args) location C:\Users\DefenderCheck\DefenderCheck\DefenderCheck\Program.cs: line number 14

windows:1809
vs:2015
.net:4.7.2

**Comment by jeffmcjunkin** [comment]
Use the `dev` branch, I had the same issue otherwise.

**Comment by matterpreter** [comment]
Please make sure you are using the latest version. `Setup()` was removed for this reason.
